CREATE DATABASE IF NOT EXISTS yd_note_workers;
USE yd_note_workers;

CREATE TABLE IF NOT EXISTS yd_note_workers (
  ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  Sahe VARCHAR(255) NOT NULL,
  FullName VARCHAR(255) NOT NULL,
  Note TEXT NOT NULL,
  timestamp DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

